### ISSUE TITLE
What is the recommended way of using oscar.py in one of the OSCAR servers?

### ISSUE THREAD

**Issue by hehao98** [ssc-oscar/oscar.py#4]
Excuse me for posting an issue here but I don't know a better place to ask this question.
 
I'm a student from Peking University, under supervision of Prof. Minghui Zhou, and I plan to do some research on the World of Code database. 

I think `oscar.py` is already installed on the server, but some of its dependency is missing. An example is

```
bash-4.2$ python
Python 2.7.5 (default, Sep 12 2018, 05:31:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oscar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/oscar.py", line 2, in <module>
ImportError: No module named lzf
```

However, I cannot install new python packages using `easy_install` because python development environment is missing, and I cannot fix this without root access. I wonder that I might have did all these things completely wrong. Should I use some sort of virtual environment to install all the dependencies and run my script?

**Comment by audrism** [comment]
Thats a good place to ask. What is the exact server you happen to use? (hostname will tell)

**Comment by hehao98** [comment]
heh@da2.eecs.utk.edu

**Comment by audrism** [comment]
try now

**Comment by hehao98** [comment]
It seems that I still cannot import oscar.py without error...
```
-bash-4.2$ python 
Python 2.7.5 (default, Sep 12 2018, 05:31:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oscar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/oscar.py", line 2, in <module>
ImportError: No module named lzf
```
Nor can I use `easy_install` to fix dependency errors...
```
-bash-4.2$ easy_install --user oscar
Searching for oscar
Best match: oscar 1.1.0
Processing oscar-1.1.0-py2.7.egg
oscar 1.1.0 is already the active version in easy-install.pth

Using /export/data/dahome/heh/.local/lib/python2.7/site-packages/oscar-1.1.0-py2.7.egg
Processing dependencies for oscar
Searching for tokyocabinet
Reading https://pypi.python.org/simple/tokyocabinet/
Best match: tokyocabinet 0.6
Downloading https://files.pythonhosted.org/packages/9c/d1/e71c5c7e6a083afc9dedd8c4b10d24364328782970c90feaf45f39131ce2/tokyocabinet-0.6.tar.gz#sha256=72165e6a82703b238f1ad7c61935d5527fa7986ec8900d1327c41e227be6ef70
Processing tokyocabinet-0.6.tar.gz
Writing /tmp/easy_install-gT2eHC/tokyocabinet-0.6/setup.cfg
Running tokyocabinet-0.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gT2eHC/tokyocabinet-0.6/egg-dist-tmp-fy9spF
tokyocabinet/btree.c:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

**Comment by audrism** [comment]
Ok, try da3 for a while, it should have oscar set up

**Comment by hehao98** [comment]
It works on da3. Thanks!

**Comment by audrism** [comment]
Please try da2, should work now
